name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e
      - name: Compile
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ -shared -fPIC main.cpp -o libOBLIVION.so
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OBLIVION_LIBRARY
          path: libOBLIVION.so
