name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.4.7075529"
          ${ANDROID_HOME}/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ -shared -fPIC main.cpp -o libOBLIVION.so
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: OBLIVION_LIBRARY
          path: libOBLIVION.so
